name: Push to S3

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install AWS
        run: npm i -g aws-sdk
      - name: Install Vite
        run: npm i -g vite
      - name: Configure AWS
        run: aws configure set aws_access_key_id ${{ secrets.AWS_KEY_ID }}
      - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY}}
      - run: aws configure set default.region eu-north-1
      - name: Install dependencies
        run: npm i
      - run: npm run build
      - name: Upload to S3
        run: aws s3 cp ./dist s3://${{ secrets.S3_BUCKET }} --recursive
